### ISSUE TITLE
The '/mentees unassigned' command returns a row of lines containing a single word '@undefined'

### ISSUE THREAD

**Issue by Hiren-Mehta** [OperationCode/operationcode_slash_commands#5]
This is the output that I get in Slack for this command

`*Mentees without mentors: *
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined
@undefined`

I suppose each such line corresponds to a mentee waiting for a mentor but the actual name is not shown

**Comment by mbach04** [comment]
Caused by a rollback during our setup & troubleshooting deployment. Good to go.
